import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';

/**
 * Generate environment configuration templates for different stacks
 */
const envTemplates = {
    nestjs: (database, projectName) => {
        let dbConfig = '';

        if (database === 'postgresql') {
            dbConfig = `# Database Configuration (PostgreSQL)
DB_HOST=postgres
DB_PORT=5432
DB_USERNAME=user
DB_PASSWORD=password
DB_DATABASE=${projectName}`;
        } else if (database === 'mysql') {
            dbConfig = `# Database Configuration (MySQL)
DB_HOST=mysql
DB_PORT=3306
DB_USERNAME=user
DB_PASSWORD=password
DB_DATABASE=${projectName}`;
        } else if (database === 'mongodb') {
            dbConfig = `# Database Configuration (MongoDB)
MONGO_URI=mongodb://mongo:27017/${projectName}`;
        }

        return `# NestJS Environment Configuration
# Generated by Agent Kit CLI

${dbConfig}

# App Configuration
PORT=3000
NODE_ENV=development
`;
    },

    laravel: (database, projectName) => {
        let dbConnection = 'mysql';
        let dbHost = 'mysql';
        let dbPort = '3306';

        if (database === 'postgresql') {
            dbConnection = 'pgsql';
            dbHost = 'postgres';
            dbPort = '5432';
        } else if (database === 'mongodb') {
            dbConnection = 'mongodb';
            dbHost = 'mongo';
            dbPort = '27017';
        }

        return `APP_NAME=Laravel
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost:8000

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=${dbConnection}
DB_HOST=${dbHost}
DB_PORT=${dbPort}
DB_DATABASE=${projectName}
DB_USERNAME=user
DB_PASSWORD=password

BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

MEMCACHED_HOST=127.0.0.1

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="\${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_HOST=
PUSHER_PORT=443
PUSHER_SCHEME=https
PUSHER_APP_CLUSTER=mt1

VITE_APP_NAME="\${APP_NAME}"
VITE_PUSHER_APP_KEY="\${PUSHER_APP_KEY}"
VITE_PUSHER_HOST="\${PUSHER_HOST}"
VITE_PUSHER_PORT="\${PUSHER_PORT}"
VITE_PUSHER_SCHEME="\${PUSHER_SCHEME}"
VITE_PUSHER_APP_CLUSTER="\${PUSHER_APP_CLUSTER}"
`;
    },

    nextjs: (database, projectName) => {
        let databaseUrl = '';

        if (database === 'postgresql') {
            databaseUrl = `DATABASE_URL=postgresql://user:password@postgres:5432/${projectName}`;
        } else if (database === 'mysql') {
            databaseUrl = `DATABASE_URL=mysql://user:password@mysql:3306/${projectName}`;
        } else if (database === 'mongodb') {
            databaseUrl = `DATABASE_URL=mongodb://mongo:27017/${projectName}`;
        }

        return `# Next.js Environment Configuration
# Generated by Agent Kit CLI

${databaseUrl}

# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:3000
NEXT_PUBLIC_APP_NAME=${projectName}

# Environment
NODE_ENV=development
`;
    },

    nuxt: (database, projectName) => {
        let databaseUrl = '';

        if (database === 'postgresql') {
            databaseUrl = `DATABASE_URL=postgresql://user:password@postgres:5432/${projectName}`;
        } else if (database === 'mysql') {
            databaseUrl = `DATABASE_URL=mysql://user:password@mysql:3306/${projectName}`;
        } else if (database === 'mongodb') {
            databaseUrl = `DATABASE_URL=mongodb://mongo:27017/${projectName}`;
        }

        return `# Nuxt Environment Configuration
# Generated by Agent Kit CLI

${databaseUrl}

# API Configuration
NUXT_PUBLIC_API_BASE=http://localhost:3000
NUXT_PUBLIC_APP_NAME=${projectName}

# Environment
NODE_ENV=development
`;
    },

    go: (database, projectName) => {
        let dbConfig = '';

        if (database === 'postgresql') {
            dbConfig = `# Database Configuration (PostgreSQL)
DB_HOST=postgres
DB_PORT=5432
DB_USER=user
DB_PASSWORD=password
DB_NAME=${projectName}
DB_SSLMODE=disable`;
        } else if (database === 'mysql') {
            dbConfig = `# Database Configuration (MySQL)
DB_HOST=mysql
DB_PORT=3306
DB_USER=user
DB_PASSWORD=password
DB_NAME=${projectName}`;
        } else if (database === 'mongodb') {
            dbConfig = `# Database Configuration (MongoDB)
MONGO_URI=mongodb://mongo:27017/${projectName}`;
        }

        return `# Go Application Environment Configuration
# Generated by Agent Kit CLI

${dbConfig}

# App Configuration
PORT=8080
GIN_MODE=debug
`;
    },

    express: (database, projectName) => {
        let dbConfig = '';

        if (database === 'postgresql') {
            dbConfig = `# Database Configuration (PostgreSQL)
DB_HOST=postgres
DB_PORT=5432
DB_USER=user
DB_PASSWORD=password
DB_NAME=${projectName}`;
        } else if (database === 'mysql') {
            dbConfig = `# Database Configuration (MySQL)
DB_HOST=mysql
DB_PORT=3306
DB_USER=user
DB_PASSWORD=password
DB_NAME=${projectName}`;
        } else if (database === 'mongodb') {
            dbConfig = `# Database Configuration (MongoDB)
MONGO_URI=mongodb://mongo:27017/${projectName}`;
        }

        return `# Express Environment Configuration
# Generated by Agent Kit CLI

${dbConfig}

# App Configuration
PORT=3000
NODE_ENV=development
`;
    },

    react: (database, projectName) => {
        let databaseUrl = '';

        if (database === 'postgresql') {
            databaseUrl = `VITE_DATABASE_URL=postgresql://user:password@postgres:5432/${projectName}`;
        } else if (database === 'mysql') {
            databaseUrl = `VITE_DATABASE_URL=mysql://user:password@mysql:3306/${projectName}`;
        } else if (database === 'mongodb') {
            databaseUrl = `VITE_DATABASE_URL=mongodb://mongo:27017/${projectName}`;
        }

        return `# React (Vite) Environment Configuration
# Generated by Agent Kit CLI

${databaseUrl}

# API Configuration
VITE_API_URL=http://localhost:3000
VITE_APP_NAME=${projectName}
`;
    },

    vue: (database, projectName) => {
        let databaseUrl = '';

        if (database === 'postgresql') {
            databaseUrl = `VITE_DATABASE_URL=postgresql://user:password@postgres:5432/${projectName}`;
        } else if (database === 'mysql') {
            databaseUrl = `VITE_DATABASE_URL=mysql://user:password@mysql:3306/${projectName}`;
        } else if (database === 'mongodb') {
            databaseUrl = `VITE_DATABASE_URL=mongodb://mongo:27017/${projectName}`;
        }

        return `# Vue (Vite) Environment Configuration
# Generated by Agent Kit CLI

${databaseUrl}

# API Configuration
VITE_API_URL=http://localhost:3000
VITE_APP_NAME=${projectName}
`;
    },

    angular: (database, projectName) => {
        let databaseUrl = '';

        if (database === 'postgresql') {
            databaseUrl = `DATABASE_URL=postgresql://user:password@postgres:5432/${projectName}`;
        } else if (database === 'mysql') {
            databaseUrl = `DATABASE_URL=mysql://user:password@mysql:3306/${projectName}`;
        } else if (database === 'mongodb') {
            databaseUrl = `DATABASE_URL=mongodb://mongo:27017/${projectName}`;
        }

        return `# Angular Environment Configuration
# Generated by Agent Kit CLI

${databaseUrl}

# API Configuration
NG_APP_API_URL=http://localhost:3000
NG_APP_NAME=${projectName}
`;
    }
};

/**
 * Determine the correct .env filename for each stack
 */
const getEnvFileName = (stack) => {
    switch (stack) {
        case 'nextjs':
            return '.env.local';
        case 'nuxt':
        case 'nestjs':
        case 'laravel':
        case 'go':
        case 'express':
        case 'react':
        case 'vue':
        case 'angular':
        default:
            return '.env';
    }
};

/**
 * Stacks that actually need .env files for database configuration
 * Pure frontend stacks (React, Vue, Angular, Next.js, Nuxt) don't need .env for basic operation
 */
const BACKEND_STACKS_NEEDING_ENV = ['nestjs', 'laravel', 'go', 'express', 'python'];

/**
 * Generate .env file with database configuration
 * @param {string} stack - Technology stack (nestjs, laravel, nextjs, etc.)
 * @param {string} database - Database type (postgresql, mysql, mongodb, none)
 * @param {string} projectName - Project name for database name
 * @param {string} targetDir - Target directory to create .env file
 */
async function generateEnvFile(stack, database, projectName, targetDir) {
    // Skip if no database selected
    if (!database || database === 'none') {
        console.log(chalk.dim('  ℹ No database selected, skipping .env generation'));
        return;
    }

    // Skip .env generation for pure frontend stacks
    // They don't need database configuration to run
    if (!BACKEND_STACKS_NEEDING_ENV.includes(stack)) {
        console.log(chalk.dim(`  ℹ Skipping .env for ${stack} (frontend stack doesn't need database config)`));
        return;
    }

    // Get the appropriate template
    const templateFn = envTemplates[stack];
    if (!templateFn) {
        console.log(chalk.yellow(`⚠ No .env template found for stack: ${stack}`));
        return;
    }

    // Generate content
    const envContent = templateFn(database, projectName);

    // Determine filename
    const envFileName = getEnvFileName(stack);
    const envFilePath = path.join(targetDir, envFileName);

    try {
        // Write .env file
        await fs.writeFile(envFilePath, envContent, 'utf8');
        console.log(chalk.green(`✓ Created ${envFileName} with ${database} configuration`));

        // For Laravel, also generate APP_KEY
        if (stack === 'laravel') {
            console.log(chalk.cyan('ℹ Remember to run: php artisan key:generate'));
        }

    } catch (error) {
        console.error(chalk.red(`✗ Failed to create ${envFileName}:`), error.message);
    }
}

export { generateEnvFile };
